# Target specific macros
TARGET = LineFollower
TARGET_SOURCES = \
	lightvalueeventdispatchertask.c \
	linefollowertask.c \
	toucheventdispatchertask.c
TOPPERS_OSEK_OIL_SOURCE = ./LineFollower.oil

# Don't modify below part
include ../../OSEK_EV3/OSEK_EV3.mak
 
