# Target specific macros
TARGET = TwoTasks
TARGET_SOURCES = \
	LowPrioTask.c \
	HighPrioTask.c
TOPPERS_OSEK_OIL_SOURCE = ./TwoTasks.oil

# Don't modify below part
EV3OSEK_ROOT = ../..
include ../../OSEK_EV3/OSEK_EV3.mak
 
