# Target specific macros
TARGET = OneTaskButtons
TARGET_SOURCES = \
	onetaskbuttons.c 
TOPPERS_OSEK_OIL_SOURCE = ./OneTaskButtons.oil

# Don't modify below part
EV3OSEK_ROOT = ../..
include ../../OSEK_EV3/OSEK_EV3.mak
 
