# Target specific macros
TARGET = AlarmTwoTasksNonPreemptive
TARGET_SOURCES = \
	Task1.c \
	Task2.c
TOPPERS_OSEK_OIL_SOURCE = ./AlarmTwoTasksNonPreemptive.oil

# Don't modify below part
EV3OSEK_ROOT = ../..
include ../../OSEK_EV3/OSEK_EV3.mak
 
