# Target specific macros
TARGET = AlarmTwoTasksResource
TARGET_SOURCES = \
	Task1.c \
	Task2.c
TOPPERS_OSEK_OIL_SOURCE = ./AlarmTwoTasksResource.oil

# Don't modify below part
include ../../OSEK_EV3/OSEK_EV3.mak
 
